import type { ShadcnTheme, ShadcnThemeStyles } from './types';

export function formatColorName(key: string) {
    return key
        .replace(/([A-Z])/g, ' $1')
        .replace(/^./, str => str.toUpperCase())
        .trim();
};

export const colorSegments: Record<string, Array<keyof ShadcnTheme>> = {
    'Primary Colors': [
        'background',
        'foreground',
        'primary',
        'primaryForeground',
    ],
    'Accents & Muted': [
        'secondary',
        'secondaryForeground',
        'muted',
        'mutedForeground',
        'accent',
        'accentForeground',
    ],
    'Surfaces & Containers': [
        'card',
        'cardForeground',
        'popover',
        'popoverForeground',
    ],
    'System & Feedback': [
        'destructive',
        'border',
        'input',
        'ring',
    ],
    'Sidebar': [
        'sidebar',
        'sidebarForeground',
        'sidebarPrimary',
        'sidebarPrimaryForeground',
        'sidebarAccent',
        'sidebarAccentForeground',
        'sidebarBorder',
        'sidebarRing',
    ],
    'Charts': [
        'chart1',
        'chart2',
        'chart3',
        'chart4',
        'chart5',
    ],
};

export const previewColors: Array<keyof ShadcnTheme> = [
    'primary', 'secondary', 'accent', 'foreground', 'background',
];

export const defaultThemeId = 'x'.repeat(16);

export const defaultTheme: ShadcnThemeStyles = {
    id: defaultThemeId,
    name: 'Default Theme',
    light: {
        radius: '0.625rem',
        background: 'oklch(1 0 0)',
        foreground: 'oklch(0.145 0 0)',
        card: 'oklch(1 0 0)',
        cardForeground: 'oklch(0.145 0 0)',
        popover: 'oklch(1 0 0)',
        popoverForeground: 'oklch(0.145 0 0)',
        primary: 'oklch(0.205 0 0)',
        primaryForeground: 'oklch(0.985 0 0)',
        secondary: 'oklch(0.97 0 0)',
        secondaryForeground: 'oklch(0.205 0 0)',
        muted: 'oklch(0.97 0 0)',
        mutedForeground: 'oklch(0.556 0 0)',
        accent: 'oklch(0.97 0 0)',
        accentForeground: 'oklch(0.205 0 0)',
        destructive: 'oklch(0.577 0.245 27.325)',
        border: 'oklch(0.922 0 0)',
        input: 'oklch(0.922 0 0)',
        ring: 'oklch(0.708 0 0)',
        chart1: 'oklch(0.646 0.222 41.116)',
        chart2: 'oklch(0.6 0.118 184.704)',
        chart3: 'oklch(0.398 0.07 227.392)',
        chart4: 'oklch(0.828 0.189 84.429)',
        chart5: 'oklch(0.769 0.188 70.08)',
        sidebar: 'oklch(0.985 0 0)',
        sidebarForeground: 'oklch(0.145 0 0)',
        sidebarPrimary: 'oklch(0.205 0 0)',
        sidebarPrimaryForeground: 'oklch(0.985 0 0)',
        sidebarAccent: 'oklch(0.97 0 0)',
        sidebarAccentForeground: 'oklch(0.205 0 0)',
        sidebarBorder: 'oklch(0.922 0 0)',
        sidebarRing: 'oklch(0.708 0 0)',
    },
    dark: {
        radius: '0.625rem',
        background: 'oklch(0.145 0 0)',
        foreground: 'oklch(0.985 0 0)',
        card: 'oklch(0.205 0 0)',
        cardForeground: 'oklch(0.985 0 0)',
        popover: 'oklch(0.205 0 0)',
        popoverForeground: 'oklch(0.985 0 0)',
        primary: 'oklch(0.922 0 0)',
        primaryForeground: 'oklch(0.205 0 0)',
        secondary: 'oklch(0.269 0 0)',
        secondaryForeground: 'oklch(0.985 0 0)',
        muted: 'oklch(0.269 0 0)',
        mutedForeground: 'oklch(0.708 0 0)',
        accent: 'oklch(0.269 0 0)',
        accentForeground: 'oklch(0.985 0 0)',
        destructive: 'oklch(0.704 0.191 22.216)',
        border: 'oklch(1 0 0 / 10%)',
        input: 'oklch(1 0 0 / 15%)',
        ring: 'oklch(0.556 0 0)',
        chart1: 'oklch(0.488 0.243 264.376)',
        chart2: 'oklch(0.696 0.17 162.48)',
        chart3: 'oklch(0.769 0.188 70.08)',
        chart4: 'oklch(0.627 0.265 303.9)',
        chart5: 'oklch(0.645 0.246 16.439)',
        sidebar: 'oklch(0.205 0 0)',
        sidebarForeground: 'oklch(0.985 0 0)',
        sidebarPrimary: 'oklch(0.488 0.243 264.376)',
        sidebarPrimaryForeground: 'oklch(0.985 0 0)',
        sidebarAccent: 'oklch(0.269 0 0)',
        sidebarAccentForeground: 'oklch(0.985 0 0)',
        sidebarBorder: 'oklch(1 0 0 / 10%)',
        sidebarRing: 'oklch(0.556 0 0)',
    },
    fontMono: '',
    fontSans: '',
    fontSerif: '',
};

export const premadeThemes: Array<ShadcnThemeStyles> = [
    {
        id: 'dracula',
        name: 'Dracula',
        fontSans: 'geist',
        fontSerif: 'geist-sans',
        fontMono: 'geist-mono',
        dark: {
            radius: '0.375rem',
            background: '#282a36',
            foreground: '#f8f8f2',
            card: '#282a36',
            cardForeground: '#f8f8f2',
            popover: '#282a36',
            popoverForeground: '#f8f8f2',
            primary: '#bd93f9',
            primaryForeground: '#ffffff',
            secondary: '#44475a',
            secondaryForeground: '#f8f8f2',
            muted: '#44475a',
            mutedForeground: '#6272a4',
            accent: '#ff5555',
            accentForeground: '#ffffff',
            destructive: '#ff5555',
            border: '#44475a',
            input: '#44475a',
            ring: '#ff79c6',
            chart1: '#ff5555',
            chart2: '#50fa7b',
            chart3: '#f1fa8c',
            chart4: '#bd93f9',
            chart5: '#ff79c6',
            sidebar: '#282a36',
            sidebarForeground: '#f8f8f2',
            sidebarPrimary: '#bd93f9',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#ff5555',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#44475a',
            sidebarRing: '#ff79c6',
        },
        light: {
            radius: '0.375rem',
            background: '#ffffff',
            foreground: '#282a36',
            card: '#ffffff',
            cardForeground: '#282a36',
            popover: '#ffffff',
            popoverForeground: '#282a36',
            primary: '#bd93f9',
            primaryForeground: '#ffffff',
            secondary: '#f1fa8c',
            secondaryForeground: 'rgb(40, 42, 54)',
            muted: '#f1fa8c',
            mutedForeground: 'rgb(98, 114, 164)',
            accent: '#ff5555',
            accentForeground: '#ffffff',
            destructive: '#ff5555',
            border: '#f1fa8c',
            input: '#f1fa8c',
            ring: '#ff79c6',
            chart1: '#ff5555',
            chart2: '#50fa7b',
            chart3: '#f1fa8c',
            chart4: '#bd93f9',
            chart5: '#ff79c6',
            sidebar: '#ffffff',
            sidebarForeground: '#282a36',
            sidebarPrimary: '#bd93f9',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#ff5555',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#f1fa8c',
            sidebarRing: '#ff79c6',
        },
    },
    {
        fontMono: '',
        fontSans: '',
        fontSerif: '',
        id: 'catppuccin',
        name: 'Catppuccin',
        dark: {
            radius: '0.5rem',
            background: '#1e1e2e',
            foreground: '#cdd6f4',
            card: '#181825',
            cardForeground: '#cdd6f4',
            popover: '#181825',
            popoverForeground: '#cdd6f4',
            primary: '#89b4fa',
            primaryForeground: '#11111b',
            secondary: '#585b70',
            secondaryForeground: '#cdd6f4',
            muted: '#313244',
            mutedForeground: '#a6adc8',
            accent: '#585b70',
            accentForeground: '#cdd6f4',
            destructive: '#f38ba8',
            border: '#313244',
            input: '#313244',
            ring: '#89b4fa',
            chart1: '#f5c2e7',
            chart2: '#cba6f7',
            chart3: '#74c7ec',
            chart4: '#94e2d5',
            chart5: '#a6e3a1',
            sidebar: '#11111b',
            sidebarForeground: '#cdd6f4',
            sidebarPrimary: '#89b4fa',
            sidebarPrimaryForeground: '#11111b',
            sidebarAccent: '#313244',
            sidebarAccentForeground: '#cdd6f4',
            sidebarBorder: '#313244',
            sidebarRing: '#89b4fa',
        },
        light: {
            radius: '0.5rem',
            background: '#eff1f5',
            foreground: '#4c4f69',
            card: '#e6e9ef',
            cardForeground: '#4c4f69',
            popover: '#e6e9ef',
            popoverForeground: '#4c4f69',
            primary: '#1e66f5',
            primaryForeground: '#dce0e8',
            secondary: '#9ca0b0',
            secondaryForeground: '#4c4f69',
            muted: '#ccd0da',
            mutedForeground: '#7c7f93',
            accent: '#9ca0b0',
            accentForeground: '#4c4f69',
            destructive: '#d20f39',
            border: '#bcc0cc',
            input: '#bcc0cc',
            ring: '#1e66f5',
            chart1: '#e64553',
            chart2: '#fe640b',
            chart3: '#df8e1d',
            chart4: '#40a02b',
            chart5: '#04a5e5',
            sidebar: '#e6e9ef',
            sidebarForeground: '#4c4f69',
            sidebarPrimary: '#1e66f5',
            sidebarPrimaryForeground: '#dce0e8',
            sidebarAccent: '#bcc0cc',
            sidebarAccentForeground: '#4c4f69',
            sidebarBorder: '#bcc0cc',
            sidebarRing: '#1e66f5',
        },
    },
    {
        id: 'hacker',
        name: 'Hacker',
        dark: {
            radius: '0rem',
            background: '#000000',
            foreground: '#c5ffd0',
            card: '#0d0d0d',
            cardForeground: '#c5ffd0',
            popover: '#0d0d0d',
            popoverForeground: '#c5ffd0',
            primary: '#5dff7a',
            primaryForeground: '#1a1a1a',
            secondary: '#4dff88',
            secondaryForeground: '#1a1a1a',
            muted: '#262626',
            mutedForeground: '#7affaa',
            accent: '#6fff91',
            accentForeground: '#1a1a1a',
            destructive: '#ff6b4a',
            border: '#333333',
            input: '#1a1a1a',
            ring: '#8dffaa',
            chart1: '#5dff7a',
            chart2: '#5dd4ff',
            chart3: '#a85dff',
            chart4: '#ff5d9d',
            chart5: '#ff8c5d',
            sidebar: '#0d0d0d',
            sidebarForeground: '#c5ffd0',
            sidebarPrimary: '#5dff7a',
            sidebarPrimaryForeground: '#1a1a1a',
            sidebarAccent: '#6fff91',
            sidebarAccentForeground: '#1a1a1a',
            sidebarBorder: '#333333',
            sidebarRing: '#8dffaa',
        },
        light: {
            radius: '0rem',
            background: '#ffffff',
            foreground: '#004d1a',
            card: '#f2f2f2',
            cardForeground: '#004d1a',
            popover: '#f2f2f2',
            popoverForeground: '#004d1a',
            primary: '#006b26',
            primaryForeground: '#ffffff',
            secondary: '#00802e',
            secondaryForeground: '#ffffff',
            muted: '#e6e6e6',
            mutedForeground: '#00662b',
            accent: '#005c1f',
            accentForeground: '#ffffff',
            destructive: '#ff6b4a',
            border: '#cccccc',
            input: '#fafafa',
            ring: '#00b347',
            chart1: '#006b26',
            chart2: '#005580',
            chart3: '#4d0080',
            chart4: '#800033',
            chart5: '#803300',
            sidebar: '#f2f2f2',
            sidebarForeground: '#004d1a',
            sidebarPrimary: '#006b26',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#005c1f',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#cccccc',
            sidebarRing: '#00b347',
        },
        fontSans: 'jetbrains-mono',
        fontSerif: '',
        fontMono: 'jetbrains-mono',
    },
    {
        name: 'Pink',
        dark: {
            radius: '1rem',
            background: '#1a001a',
            foreground: '#ff66cc',
            card: '#2b002b',
            cardForeground: '#ff66cc',
            popover: '#2b002b',
            popoverForeground: '#ff66cc',
            primary: '#ff33aa',
            primaryForeground: '#1a001a',
            secondary: '#ff0099',
            secondaryForeground: '#1a001a',
            muted: '#150015',
            mutedForeground: '#ff3399',
            accent: 'rgb(255, 102, 204)',
            accentForeground: 'rgb(255, 55, 178)',
            destructive: '#ff0033',
            border: '#440044',
            input: '#2b002b',
            ring: '#ff66cc',
            chart1: '#ff66cc',
            chart2: '#ff33aa',
            chart3: '#ff0099',
            chart4: '#cc0066',
            chart5: '#99004d',
            sidebar: '#1a001a',
            sidebarForeground: '#ff66cc',
            sidebarPrimary: '#ff66cc',
            sidebarPrimaryForeground: '#1a001a',
            sidebarAccent: '#ff33aa',
            sidebarAccentForeground: '#1a001a',
            sidebarBorder: '#440044',
            sidebarRing: '#ff66cc',
        },
        light: {
            radius: '1rem',
            background: '#ffe6f2',
            foreground: '#660033',
            card: '#fff0f7',
            cardForeground: '#660033',
            popover: '#fff0f7',
            popoverForeground: '#660033',
            primary: '#ff66cc',
            primaryForeground: '#ffffff',
            secondary: '#ff33aa',
            secondaryForeground: '#ffffff',
            muted: '#ffe0eb',
            mutedForeground: '#660033',
            accent: '#ff66cc',
            accentForeground: '#ffffff',
            destructive: '#ff0033',
            border: '#ffb3d9',
            input: '#fff0f7',
            ring: '#ff66cc',
            chart1: '#ff66cc',
            chart2: '#ff33aa',
            chart3: '#ff0099',
            chart4: '#cc0066',
            chart5: '#99004d',
            sidebar: '#ffe6f2',
            sidebarForeground: '#660033',
            sidebarPrimary: '#ff66cc',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#ff33aa',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#ffb3d9',
            sidebarRing: '#ff66cc',
        },
        fontSans: '',
        fontSerif: '',
        fontMono: '',
        id: '8cIjFv20Ym2KhWS2',
    },
    {
        name: 'Nord',
        dark: {
            radius: '0.5rem',
            background: '#2E3440',
            foreground: '#D8DEE9',
            card: '#3B4252',
            cardForeground: '#D8DEE9',
            popover: '#3B4252',
            popoverForeground: '#D8DEE9',
            primary: '#5E81AC',
            primaryForeground: '#ECEFF4',
            secondary: '#88C0D0',
            secondaryForeground: '#2E3440',
            muted: '#4C566A',
            mutedForeground: '#D8DEE9',
            accent: '#81A1C1',
            accentForeground: '#2E3440',
            destructive: '#BF616A',
            border: '#4C566A',
            input: '#434C5E',
            ring: '#81A1C1',
            chart1: '#BF616A',
            chart2: '#D08770',
            chart3: '#EBCB8B',
            chart4: '#A3BE8C',
            chart5: '#88C0D0',
            sidebar: '#3B4252',
            sidebarForeground: '#D8DEE9',
            sidebarPrimary: '#5E81AC',
            sidebarPrimaryForeground: '#ECEFF4',
            sidebarAccent: '#81A1C1',
            sidebarAccentForeground: '#2E3440',
            sidebarBorder: '#4C566A',
            sidebarRing: '#81A1C1',
        },
        light: {
            radius: '0.5rem',
            background: '#ECEFF4',
            foreground: '#2E3440',
            card: '#D8DEE9',
            cardForeground: '#2E3440',
            popover: '#D8DEE9',
            popoverForeground: '#2E3440',
            primary: '#5E81AC',
            primaryForeground: '#ECEFF4',
            secondary: '#88C0D0',
            secondaryForeground: '#2E3440',
            muted: '#E5E9F0',
            mutedForeground: '#4C566A',
            accent: '#81A1C1',
            accentForeground: '#2E3440',
            destructive: '#BF616A',
            border: '#D8DEE9',
            input: '#FFFFFF',
            ring: '#81A1C1',
            chart1: '#BF616A',
            chart2: '#D08770',
            chart3: '#EBCB8B',
            chart4: '#A3BE8C',
            chart5: '#88C0D0',
            sidebar: '#D8DEE9',
            sidebarForeground: '#2E3440',
            sidebarPrimary: '#5E81AC',
            sidebarPrimaryForeground: '#ECEFF4',
            sidebarAccent: '#81A1C1',
            sidebarAccentForeground: '#2E3440',
            sidebarBorder: '#D8DEE9',
            sidebarRing: '#81A1C1',
        },
        fontSans: '',
        fontSerif: '',
        fontMono: '',
        id: '74Aw0qiKqD8LWrf6',
    },
    {
        name: 'Fireflies',
        dark: {
            radius: '0.5rem',
            background: '#0a0a0a',
            foreground: '#e0e0e0',
            card: '#111111',
            cardForeground: '#e0e0e0',
            popover: '#111111',
            popoverForeground: '#e0e0e0',
            primary: '#ffdd57',
            primaryForeground: '#0a0a0a',
            secondary: '#ff8800',
            secondaryForeground: '#0a0a0a',
            muted: '#1a1a1a',
            mutedForeground: '#8a8a8a',
            accent: '#66ff66',
            accentForeground: '#0a0a0a',
            destructive: '#ff3333',
            border: '#222222',
            input: '#1a1a1a',
            ring: '#ffdd57',
            chart1: '#ffdd57',
            chart2: '#ff8800',
            chart3: '#66ff66',
            chart4: '#3399ff',
            chart5: '#ff33aa',
            sidebar: '#0a0a0a',
            sidebarForeground: '#e0e0e0',
            sidebarPrimary: '#ffdd57',
            sidebarPrimaryForeground: '#0a0a0a',
            sidebarAccent: '#66ff66',
            sidebarAccentForeground: '#0a0a0a',
            sidebarBorder: '#222222',
            sidebarRing: '#ffdd57',
        },
        light: {
            radius: '0.5rem',
            background: '#ffffff',
            foreground: '#0a0a0a',
            card: '#f9f9f9',
            cardForeground: '#0a0a0a',
            popover: '#f9f9f9',
            popoverForeground: '#0a0a0a',
            primary: '#ff8800',
            primaryForeground: '#ffffff',
            secondary: '#ffdd57',
            secondaryForeground: '#0a0a0a',
            muted: '#f0f0f0',
            mutedForeground: '#5a5a5a',
            accent: '#006600',
            accentForeground: '#ffffff',
            destructive: '#d32f2f',
            border: '#e0e0e0',
            input: '#ffffff',
            ring: '#ff8800',
            chart1: '#ff8800',
            chart2: '#ffdd57',
            chart3: '#006600',
            chart4: '#3399ff',
            chart5: '#ff33aa',
            sidebar: '#ffffff',
            sidebarForeground: '#0a0a0a',
            sidebarPrimary: '#ff8800',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#006600',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#e0e0e0',
            sidebarRing: '#ff8800',
        },
        fontSans: '',
        fontSerif: '',
        fontMono: '',
        id: 'pDzhfH76yJd1FxwZ',
    },
    {
        name: 'Playfair',
        dark: {
            radius: '0.25rem',
            background: '#0b0d12',
            foreground: '#e0e5f2',
            card: '#11141c',
            cardForeground: '#e0e5f2',
            popover: '#11141c',
            popoverForeground: '#e0e5f2',
            primary: '#ff9f1c',
            primaryForeground: '#1a1a1a',
            secondary: '#2a9d8f',
            secondaryForeground: '#1a1a1a',
            muted: '#1e2027',
            mutedForeground: '#8a8d9b',
            accent: '#e76f51',
            accentForeground: '#1a1a1a',
            destructive: '#e63946',
            border: '#262a33',
            input: '#1e2027',
            ring: '#ff9f1c',
            chart1: '#ff9f1c',
            chart2: '#2a9d8f',
            chart3: '#e76f51',
            chart4: '#e63946',
            chart5: '#a8dadc',
            sidebar: '#11141c',
            sidebarForeground: '#e0e5f2',
            sidebarPrimary: '#ff9f1c',
            sidebarPrimaryForeground: '#1a1a1a',
            sidebarAccent: '#2a9d8f',
            sidebarAccentForeground: '#1a1a1a',
            sidebarBorder: '#262a33',
            sidebarRing: '#ff9f1c',
        },
        light: {
            radius: '0.25rem',
            background: '#ffffff',
            foreground: '#1a1a1a',
            card: '#f8fafc',
            cardForeground: '#1a1a1a',
            popover: '#f8fafc',
            popoverForeground: '#1a1a1a',
            primary: '#ff9f1c',
            primaryForeground: '#ffffff',
            secondary: '#2a9d8f',
            secondaryForeground: '#ffffff',
            muted: '#f1f5f9',
            mutedForeground: '#6b7280',
            accent: '#e76f51',
            accentForeground: '#ffffff',
            destructive: '#e63946',
            border: '#e2e8f0',
            input: '#f1f5f9',
            ring: '#ff9f1c',
            chart1: '#ff9f1c',
            chart2: '#2a9d8f',
            chart3: '#e76f51',
            chart4: '#e63946',
            chart5: '#a8dadc',
            sidebar: '#f8fafc',
            sidebarForeground: '#1a1a1a',
            sidebarPrimary: '#ff9f1c',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#2a9d8f',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#e2e8f0',
            sidebarRing: '#ff9f1c',
        },
        fontSans: 'bebas-neue',
        fontSerif: 'playfair-display',
        fontMono: '',
        id: 'fireflies',
    },
    {
        name: 'Tokyo Night',
        dark: {
            radius: '0.75rem',
            background: '#1a1b26',
            foreground: 'rgb(215, 220, 242)',
            card: '#24283b',
            cardForeground: '#c0caf5',
            popover: '#24283b',
            popoverForeground: '#c0caf5',
            primary: '#7aa2f7',
            primaryForeground: '#1a1b26',
            secondary: '#bb9af7',
            secondaryForeground: '#1a1b26',
            muted: '#283046',
            mutedForeground: '#a9b1d6',
            accent: '#ff9e64',
            accentForeground: '#1a1b26',
            destructive: '#f7768e',
            border: '#414868',
            input: '#292e42',
            ring: '#7aa2f7',
            chart1: '#7aa2f7',
            chart2: '#e0af68',
            chart3: '#9ece6a',
            chart4: '#bb9af7',
            chart5: '#ff9e64',
            sidebar: '#1f2335',
            sidebarForeground: '#c0caf5',
            sidebarPrimary: '#7aa2f7',
            sidebarPrimaryForeground: '#1a1b26',
            sidebarAccent: '#ff9e64',
            sidebarAccentForeground: '#1a1b26',
            sidebarBorder: '#414868',
            sidebarRing: '#7aa2f7',
        },
        light: {
            radius: '0.75rem',
            background: '#ffffff',
            foreground: '#2e3440',
            card: '#f2f4f8',
            cardForeground: '#2e3440',
            popover: '#f2f4f8',
            popoverForeground: '#2e3440',
            primary: '#5e81ac',
            primaryForeground: '#ffffff',
            secondary: '#a3be8c',
            secondaryForeground: '#ffffff',
            muted: '#e5e9f0',
            mutedForeground: '#4c566a',
            accent: '#d08770',
            accentForeground: '#ffffff',
            destructive: '#bf616a',
            border: '#d8dee9',
            input: '#e5e9f0',
            ring: '#5e81ac',
            chart1: '#5e81ac',
            chart2: '#d08770',
            chart3: '#a3be8c',
            chart4: '#b48ead',
            chart5: '#ebcb8b',
            sidebar: '#eceff4',
            sidebarForeground: '#2e3440',
            sidebarPrimary: '#5e81ac',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#d08770',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#d8dee9',
            sidebarRing: '#5e81ac',
        },
        fontSans: 'montserrat',
        fontSerif: '',
        fontMono: 'jetbrains-mono',
        id: 'M1ZEnFu8Zc50Cdfl',
    },
    {
        name: 'Monokai',
        dark: {
            radius: '0.5rem',
            background: '#272822',
            foreground: '#f8f8f2',
            card: '#3e3d32',
            cardForeground: '#f8f8f2',
            popover: '#3e3d32',
            popoverForeground: '#f8f8f2',
            primary: '#fd971f',
            primaryForeground: '#272822',
            secondary: '#66d9ef',
            secondaryForeground: '#272822',
            muted: '#49483e',
            mutedForeground: '#a6a69c',
            accent: '#ae81ff',
            accentForeground: '#272822',
            destructive: '#f92672',
            border: '#49483e',
            input: '#3e3d32',
            ring: '#fd971f',
            chart1: '#a6e22e',
            chart2: '#fd971f',
            chart3: '#66d9ef',
            chart4: '#ae81ff',
            chart5: '#f92672',
            sidebar: '#1e1f1c',
            sidebarForeground: '#f8f8f2',
            sidebarPrimary: '#fd971f',
            sidebarPrimaryForeground: '#272822',
            sidebarAccent: '#ae81ff',
            sidebarAccentForeground: '#272822',
            sidebarBorder: '#49483e',
            sidebarRing: '#fd971f',
        },
        light: {
            radius: '0.5rem',
            background: '#f8f8f2',
            foreground: '#272822',
            card: '#ffffff',
            cardForeground: '#272822',
            popover: '#ffffff',
            popoverForeground: '#272822',
            primary: '#fd971f',
            primaryForeground: '#ffffff',
            secondary: '#66d9ef',
            secondaryForeground: '#ffffff',
            muted: '#e0e0e0',
            mutedForeground: '#5a5a5a',
            accent: '#ae81ff',
            accentForeground: '#ffffff',
            destructive: '#f92672',
            border: '#d0d0d0',
            input: '#ffffff',
            ring: '#fd971f',
            chart1: '#a6e22e',
            chart2: '#fd971f',
            chart3: '#66d9ef',
            chart4: '#ae81ff',
            chart5: '#f92672',
            sidebar: '#f0f0f0',
            sidebarForeground: '#272822',
            sidebarPrimary: '#fd971f',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#ae81ff',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#d0d0d0',
            sidebarRing: '#fd971f',
        },
        fontSans: 'inter',
        fontSerif: '',
        fontMono: '',
        id: 'De2lyVMK31JP5TcD',
    },
    {
        name: 'Notion',
        dark: {
            radius: '0.5rem',
            background: '#1a1a1a',
            foreground: '#ffffff',
            card: '#2a2a2a',
            cardForeground: '#ffffff',
            popover: '#2a2a2a',
            popoverForeground: '#ffffff',
            primary: '#e9e9e9',
            primaryForeground: '#1a1a1a',
            secondary: '#3a3a3a',
            secondaryForeground: '#ffffff',
            muted: '#3a3a3a',
            mutedForeground: '#a0a0a0',
            accent: '#e9e9e9',
            accentForeground: '#1a1a1a',
            destructive: '#ff5555',
            border: '#3a3a3a',
            input: '#2a2a2a',
            ring: '#e9e9e9',
            chart1: '#ff5555',
            chart2: '#ffcc00',
            chart3: '#55ff55',
            chart4: '#55aaff',
            chart5: '#ff55ff',
            sidebar: '#1a1a1a',
            sidebarForeground: '#ffffff',
            sidebarPrimary: '#e9e9e9',
            sidebarPrimaryForeground: '#1a1a1a',
            sidebarAccent: '#3a3a3a',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#3a3a3a',
            sidebarRing: '#e9e9e9',
        },
        light: {
            radius: '0.5rem',
            background: '#ffffff',
            foreground: '#1a1a1a',
            card: '#f5f5f5',
            cardForeground: '#1a1a1a',
            popover: '#f5f5f5',
            popoverForeground: '#1a1a1a',
            primary: '#1a1a1a',
            primaryForeground: '#ffffff',
            secondary: '#e0e0e0',
            secondaryForeground: '#1a1a1a',
            muted: '#e0e0e0',
            mutedForeground: '#606060',
            accent: '#1a1a1a',
            accentForeground: '#ffffff',
            destructive: '#ff3333',
            border: '#e0e0e0',
            input: '#f5f5f5',
            ring: '#1a1a1a',
            chart1: '#ff3333',
            chart2: '#ffb300',
            chart3: '#33ff33',
            chart4: '#3399ff',
            chart5: '#ff33ff',
            sidebar: '#ffffff',
            sidebarForeground: '#1a1a1a',
            sidebarPrimary: '#1a1a1a',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#e0e0e0',
            sidebarAccentForeground: '#1a1a1a',
            sidebarBorder: '#e0e0e0',
            sidebarRing: '1a1a1a',
        },
        fontSans: 'inter',
        fontSerif: '',
        fontMono: '',
        id: 'B6wdS4UKeYCR7dXL',
    },
    {
        name: 'Discord',
        dark: {
            radius: '0.5rem',
            background: '#313338',
            foreground: '#f2f3f5',
            card: '#2c2d31',
            cardForeground: '#f2f3f5',
            popover: '#313338',
            popoverForeground: '#f2f3f5',
            primary: '#5865f2',
            primaryForeground: '#ffffff',
            secondary: '#404249',
            secondaryForeground: '#f2f3f5',
            muted: '#1e1f22',
            mutedForeground: '#a1a3a6',
            accent: '#5865f2',
            accentForeground: '#ffffff',
            destructive: '#ed4245',
            border: '#1e1f22',
            input: '#404249',
            ring: '#5865f2',
            chart1: '#5865f2',
            chart2: '#57c7b8',
            chart3: '#faa61c',
            chart4: '#00a0f0',
            chart5: '#a15ebf',
            sidebar: '#2c2d31',
            sidebarForeground: '#f2f3f5',
            sidebarPrimary: '#5865f2',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#404249',
            sidebarAccentForeground: '#f2f3f5',
            sidebarBorder: '#1e1f22',
            sidebarRing: '#5865f2',
        },
        light: {
            radius: '0.5rem',
            background: '#ffffff',
            foreground: '#2c2d31',
            card: '#f2f3f5',
            cardForeground: '#2c2d31',
            popover: '#ffffff',
            popoverForeground: '#2c2d31',
            primary: '#5865f2',
            primaryForeground: '#ffffff',
            secondary: '#ebedef',
            secondaryForeground: '#2c2d31',
            muted: '#ebedef',
            mutedForeground: '#6a6a6a',
            accent: '#5865f2',
            accentForeground: '#ffffff',
            destructive: '#ed4245',
            border: '#d4d7db',
            input: '#ebedef',
            ring: '#5865f2',
            chart1: '#5865f2',
            chart2: '#57c7b8',
            chart3: '#faa61c',
            chart4: '#00a0f0',
            chart5: '#a15ebf',
            sidebar: '#f2f3f5',
            sidebarForeground: '#2c2d31',
            sidebarPrimary: '#5865f2',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#ebedef',
            sidebarAccentForeground: '#2c2d31',
            sidebarBorder: '#d4d7db',
            sidebarRing: '#5865f2',
        },
        fontSans: 'montserrat',
        fontSerif: '',
        fontMono: '',
        id: 'Tv7nbvZCQVFs1kpW',
    },
    {
        name: 'Dawn',
        dark: {
            radius: '0.5rem',
            background: '#0b0b0f',
            foreground: '#e5e7eb',
            card: '#111827',
            cardForeground: '#e5e7eb',
            popover: '#111827',
            popoverForeground: '#e5e7eb',
            primary: '#f59e0b',
            primaryForeground: '#0b0b0f',
            secondary: '#1f2937',
            secondaryForeground: '#e5e7eb',
            muted: '#1f2937',
            mutedForeground: '#9ca3af',
            accent: '#f59e0b',
            accentForeground: '#0b0b0f',
            destructive: '#ef4444',
            border: '#374151',
            input: '#1f2937',
            ring: '#f59e0b',
            chart1: '#f59e0b',
            chart2: '#10b981',
            chart3: '#3b82f6',
            chart4: '#f97316',
            chart5: '#8b5cf6',
            sidebar: '#111827',
            sidebarForeground: '#e5e7eb',
            sidebarPrimary: '#f59e0b',
            sidebarPrimaryForeground: '#0b0b0f',
            sidebarAccent: '#1f2937',
            sidebarAccentForeground: '#e5e7eb',
            sidebarBorder: '#374151',
            sidebarRing: '#f59e0b',
        },
        light: {
            radius: '0.5rem',
            background: '#ffffff',
            foreground: '#111827',
            card: '#ffffff',
            cardForeground: '#111827',
            popover: '#ffffff',
            popoverForeground: '#111827',
            primary: '#f59e0b',
            primaryForeground: '#ffffff',
            secondary: '#f3f4f6',
            secondaryForeground: '#111827',
            muted: '#f3f4f6',
            mutedForeground: '#6b7280',
            accent: '#f59e0b',
            accentForeground: '#ffffff',
            destructive: '#ef4444',
            border: '#e5e7eb',
            input: '#ffffff',
            ring: '#f59e0b',
            chart1: '#f59e0b',
            chart2: '#10b981',
            chart3: '#3b82f6',
            chart4: '#f97316',
            chart5: '#8b5cf6',
            sidebar: '#ffffff',
            sidebarForeground: '#111827',
            sidebarPrimary: '#f59e0b',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#f3f4f6',
            sidebarAccentForeground: '#111827',
            sidebarBorder: '#e5e7eb',
            sidebarRing: '#f59e0b',
        },
        fontSans: 'inter',
        fontSerif: 'merriweather',
        fontMono: 'overpass-mono',
        id: 'ibgP0uv80zYnfIxa',
    },
    {
        name: 'Storm',
        dark: {
            radius: '0.5rem',
            background: '#0f1422',
            foreground: '#e5e5e5',
            card: '#1a1e2e',
            cardForeground: '#f0f0f0',
            popover: '#1a1e2e',
            popoverForeground: '#f0f0f0',
            primary: '#3b82f6',
            primaryForeground: '#ffffff',
            secondary: '#232a3f',
            secondaryForeground: '#e5e5e5',
            muted: '#1d2332',
            mutedForeground: '#9a9a9a',
            accent: '#06b6d4',
            accentForeground: '#f0f0f0',
            destructive: '#ef4444',
            border: '#2a3347',
            input: '#1d2332',
            ring: '#3b82f6',
            chart1: '#60a5fa',
            chart2: '#06b6d4',
            chart3: '#a855f7',
            chart4: '#f59e0b',
            chart5: '#4ade80',
            sidebar: '#121827',
            sidebarForeground: '#e5e5e5',
            sidebarPrimary: '#3b82f6',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#06b6d4',
            sidebarAccentForeground: '#f0f0f0',
            sidebarBorder: '#2a3347',
            sidebarRing: '#3b82f6',
        },
        light: {
            radius: '0.5rem',
            background: '#e6ebf5',
            foreground: '#0a0a0a',
            card: '#d5def0',
            cardForeground: '#0a0a0a',
            popover: '#ffffff',
            popoverForeground: '#0a0a0a',
            primary: '#3b82f6',
            primaryForeground: '#ffffff',
            secondary: '#d5def0',
            secondaryForeground: '#0a0a0a',
            muted: '#e0e6f2',
            mutedForeground: '#6b6b6b',
            accent: '#06b6d4',
            accentForeground: '#ffffff',
            destructive: '#ef4444',
            border: '#c2d0e6',
            input: '#ffffff',
            ring: '#3b82f6',
            chart1: '#3b82f6',
            chart2: '#06b6d4',
            chart3: '#8b5cf6',
            chart4: '#f59e0b',
            chart5: '#22c55e',
            sidebar: '#d5def0',
            sidebarForeground: '#0a0a0a',
            sidebarPrimary: '#3b82f6',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#06b6d4',
            sidebarAccentForeground: '#ffffff',
            sidebarBorder: '#c2d0e6',
            sidebarRing: '#3b82f6',
        },
        fontSans: 'inter',
        fontSerif: '',
        fontMono: '',
        id: 'FddeZ7CKp1x2xpki',
    },
    {
        name: 'Jungle',
        dark: {
            radius: '0.5rem',
            background: '#0d130d',
            foreground: '#f0f0f0',
            card: '#1e2a1e',
            cardForeground: '#f0f0f0',
            popover: '#1e2a1e',
            popoverForeground: '#f0f0f0',
            primary: '#2a9d8f',
            primaryForeground: '#f0f0f0',
            secondary: '#264653',
            secondaryForeground: '#f0f0f0',
            muted: '#1a231a',
            mutedForeground: '#a0a0a0',
            accent: '#e9c46a',
            accentForeground: '#0d130d',
            destructive: '#e63946',
            border: '#2a3a2a',
            input: '#1a231a',
            ring: '#2a9d8f',
            chart1: '#2a9d8f',
            chart2: '#e9c46a',
            chart3: '#f4a261',
            chart4: '#e63946',
            chart5: '#264653',
            sidebar: '#0d130d',
            sidebarForeground: '#f0f0f0',
            sidebarPrimary: '#2a9d8f',
            sidebarPrimaryForeground: '#f0f0f0',
            sidebarAccent: '#e9c46a',
            sidebarAccentForeground: '#0d130d',
            sidebarBorder: '#2a3a2a',
            sidebarRing: '#2a9d8f',
        },
        light: {
            radius: '0.5rem',
            background: '#e8f5e8',
            foreground: '#0a0a0a',
            card: '#ffffff',
            cardForeground: '#0a0a0a',
            popover: '#ffffff',
            popoverForeground: '#0a0a0a',
            primary: '#2a9d8f',
            primaryForeground: '#ffffff',
            secondary: '#264653',
            secondaryForeground: '#ffffff',
            muted: '#d0e0d0',
            mutedForeground: '#5a6a5a',
            accent: '#e9c46a',
            accentForeground: '#0a0a0a',
            destructive: '#e63946',
            border: '#c0d0c0',
            input: '#ffffff',
            ring: '#2a9d8f',
            chart1: '#2a9d8f',
            chart2: '#e9c46a',
            chart3: '#f4a261',
            chart4: '#e63946',
            chart5: '#264653',
            sidebar: '#e8f5e8',
            sidebarForeground: '#0a0a0a',
            sidebarPrimary: '#2a9d8f',
            sidebarPrimaryForeground: '#ffffff',
            sidebarAccent: '#e9c46a',
            sidebarAccentForeground: '#0a0a0a',
            sidebarBorder: '#c0d0c0',
            sidebarRing: '#2a9d8f',
        },
        fontSans: '',
        fontSerif: '',
        fontMono: '',
        id: 'EbrpWapLLotWhjJY',
    },
    {
        name: 'Red',
        dark: {
            radius: '0.5rem',
            background: '#0c0a09',
            foreground: '#fafaf9',
            card: '#1c1917',
            cardForeground: '#fafaf9',
            popover: '#1c1917',
            popoverForeground: '#fafaf9',
            primary: '#dc2626',
            primaryForeground: '#fafaf9',
            secondary: '#292524',
            secondaryForeground: '#fafaf9',
            muted: '#292524',
            mutedForeground: '#a8a29e',
            accent: '#ef4444',
            accentForeground: '#fafaf9',
            destructive: '#ef4444',
            border: '#44403c',
            input: '#292524',
            ring: '#ef4444',
            chart1: '#ef4444',
            chart2: '#f87171',
            chart3: '#dc2626',
            chart4: '#b91c1c',
            chart5: '#991b1b',
            sidebar: '#1c1917',
            sidebarForeground: '#fafaf9',
            sidebarPrimary: '#dc2626',
            sidebarPrimaryForeground: '#fafaf9',
            sidebarAccent: '#ef4444',
            sidebarAccentForeground: '#fafaf9',
            sidebarBorder: '#44403c',
            sidebarRing: '#ef4444',
        },
        light: {
            radius: '0.5rem',
            background: '#ffffff',
            foreground: '#0c0a09',
            card: '#ffffff',
            cardForeground: '#0c0a09',
            popover: '#ffffff',
            popoverForeground: '#0c0a09',
            primary: '#dc2626',
            primaryForeground: '#fafaf9',
            secondary: '#f5f5f4',
            secondaryForeground: '#0c0a09',
            muted: '#f5f5f4',
            mutedForeground: '#78716c',
            accent: '#ef4444',
            accentForeground: '#fafaf9',
            destructive: '#ef4444',
            border: '#e7e5e4',
            input: '#ffffff',
            ring: '#ef4444',
            chart1: '#dc2626',
            chart2: '#ef4444',
            chart3: '#f87171',
            chart4: '#fca5a5',
            chart5: '#fee2e2',
            sidebar: '#ffffff',
            sidebarForeground: '#0c0a09',
            sidebarPrimary: '#dc2626',
            sidebarPrimaryForeground: '#fafaf9',
            sidebarAccent: '#ef4444',
            sidebarAccentForeground: '#fafaf9',
            sidebarBorder: '#e7e5e4',
            sidebarRing: '#ef4444',
        },
        fontSans: 'inter',
        fontSerif: 'lora',
        fontMono: 'fira-code',
        id: 'dBqKxcCQ1nKyRE3I',
    },
];
